// Differential oracle: runs each input in tests/vectors.json through the reference
// JavaScript dotenv and writes the observed output as a Rust source file.
//
// The expectations are *recorded*, never hand-written, so the Rust port is checked
// against what dotenv actually does rather than what we think it does.
//
//   cd scripts && npm install && npm run gen
//
// The generated file is committed; you only need node to regenerate it.

import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createRequire } from 'node:module'

const here = dirname(fileURLToPath(import.meta.url))
const require = createRequire(import.meta.url)
const dotenv = require('dotenv')

const VECTORS = join(here, '..', 'tests', 'vectors.json')
const OUT = join(here, '..', 'tests', 'support', 'vectors_generated.rs')

/** Render a JS string as a Rust `&str` literal, escaping everything non-printable-ASCII. */
function rustStr (s) {
  let out = '"'
  for (const ch of s) {
    const cp = ch.codePointAt(0)
    if (ch === '\\') out += '\\\\'
    else if (ch === '"') out += '\\"'
    else if (cp >= 0x20 && cp <= 0x7e) out += ch
    else out += `\\u{${cp.toString(16)}}`
  }
  return out + '"'
}

const vectors = JSON.parse(readFileSync(VECTORS, 'utf8'))

const seen = new Set()
for (const v of vectors) {
  if (seen.has(v.name)) throw new Error(`duplicate vector name: ${v.name}`)
  seen.add(v.name)
}

let body = ''
for (const v of vectors) {
  const parsed = dotenv.parse(v.input)
  const pairs = Object.entries(parsed)
    .map(([k, val]) => `        (${rustStr(k)}, ${rustStr(val)}),`)
    .join('\n')
  body += `    // ${v.category}: ${v.description}\n`
  body += `    Vector {\n`
  body += `        name: ${rustStr(v.name)},\n`
  body += `        category: ${rustStr(v.category)},\n`
  body += `        input: ${rustStr(v.input)},\n`
  body += pairs ? `        expected: &[\n${pairs}\n        ],\n` : `        expected: &[],\n`
  body += `    },\n`
}

const out = `// @generated by scripts/gen_expected.mjs from tests/vectors.json
// Expectations recorded from the reference implementation: dotenv@${require('dotenv/package.json').version}
// Do not edit by hand -- run \`cd scripts && npm install && npm run gen\`.

pub struct Vector {
    pub name: &'static str,
    pub category: &'static str,
    pub input: &'static str,
    pub expected: &'static [(&'static str, &'static str)],
}

pub const VECTORS: &[Vector] = &[
${body}];
`

writeFileSync(OUT, out)
// Let rustfmt own the layout, so regenerating never produces a formatting diff.
execFileSync('cargo', ['fmt'], { cwd: join(here, '..'), stdio: 'inherit' })
console.log(`wrote ${OUT} (${vectors.length} vectors, dotenv@${require('dotenv/package.json').version})`)
